FROM python:3.7
 
WORKDIR /app
COPY . /app

COPY requirements.txt requirements.txt

RUN apt-get update
RUN apt-get install default-jdk -y

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "index.py"]